### ISSUE TITLE
Feature Request: Screen Brightness Max, or White circle for low light illumination?

### ISSUE THREAD

**Issue by ThatJeffGuy** [null-dev/UniversalAuth#15]
As the title suggests

Can we get either an ability to increase screen brightness to max when it's trying to see a face, or, similar to how a front FP sensor works, add a white circle at full brightness to sort of "front flashlight" the phone?

I personally use tasker so if we can branch it out to be addressable via Tasker, I'm sure I can create and share a scene for this, or max brightness task.

Thanks guys 🌚🌚

**Comment by null-dev** [comment]
It actually does have a tasker hook.

Add an `Event > Intent Received` profile. Set the `Action` to: `ax.nd.universalauth.early-unlock`.

The profile will be triggered whenever face unlock starts/ends.

You can access the `%ax_nd_universalauth_early_unlock_mode` variable inside the profile. When face unlock starts, the profile will be triggered with that variable set to `true`. Once face unlock is finished, the profile will be triggered again, with that variable set to `false`.

**Comment by ThatJeffGuy** [comment]
Good sir

You might have made my night.

Let me work on a scene or profile and I'll post it here when complete.

Thank you 😊

**Comment by ThatJeffGuy** [comment]
Update: I have everything up and running but can't get the scene to show up on the lock screen.

Almost finished for anyone following and wanting this.

**Comment by aussiebro** [comment]
> Update: I have everything up and running but can't get the scene to show up on the lock screen.
> 
> Almost finished for anyone following and wanting this.

Yes please mate

**Comment by ThatJeffGuy** [comment]
The December update on the Pixel 6 seems to have broken this apps functionality. Can't get it to work now, which means can't keep working on the tasker profile :(
