### ISSUE TITLE
Recognized but not unlocked

### ISSUE THREAD

**Issue by Uzuhe-0630-Japan** [null-dev/UniversalAuth#18]
I am Japanese. That's why I'm not good at English.
Text may be unnatural
Will begin the main subject.
It will recognize your face and display "Welcome".
However, it does not move to the home screen or the apps screen.
If you swipe, you will be asked for your password.
I have a Pixel 6a with Android 13.
I would be happy if you could improve

**Comment by eldigo** [comment]
I'm having the same issue with android 13.1 (arrow)

Face is recognized en the Welkom tekst show.
But the screen is still locked.
