### ISSUE TITLE
Files download timing out

### ISSUE THREAD

**Issue by alejoar** [null-dev/UniversalAuth#5]
Looks like the url the app uses to get the library files is timing out: https://cloudflare-ipfs.com/ipfs/QmQNREjjXTQBDpd69gFqEreNi1dV91eSGQByqi5nXU3rBt

**Comment by null-dev** [comment]
Seems to be fixed now, thanks for the heads up!

**Comment by CryptedBytes** [comment]
Do I need to compile the app myself now? Using the released apk has this bug.
